# Generated by Django 4.1 on 2022-11-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='cod_delivery',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='statedomicile',
            name='cod_state_domicile',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
