# Generated by Django 4.1 on 2022-10-26 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sales_cod_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesdetail',
            options={},
        ),
        migrations.AlterModelTable(
            name='salesdetail',
            table=None,
        ),
    ]
