# Generated by Django 4.1 on 2022-10-29 03:42

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_salesdetail_options_alter_salesdetail_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='cod_order',
        ),
        migrations.AddField(
            model_name='order',
            name='cod_sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sales'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(core.models.OrderStatus['CREATED'], 'Creado'), (core.models.OrderStatus['PAYED'], 'Pagado'), (core.models.OrderStatus['COMPLETED'], 'Cancelado')], default=core.models.OrderStatus['CREATED'], max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='cod_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
