# Generated by Django 4.1 on 2022-10-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_order_cod_client_order_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver_cost',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='cod_order',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
