# Generated by Django 4.1 on 2022-10-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_deliver_cost_alter_order_cod_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='full_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
