# Generated by Django 4.1 on 2022-10-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_sales_full_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_product',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Precio del producto'),
        ),
    ]
