"""
Django settings for comGStore project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from telnetlib import LOGOUT
import comGStore.db as db
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

#sys.setrecursionlimit(1900)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gu%cnzl$u%&bj3=08@gry)=^+s!4j8=ujc352ou0(&_c#$hq%r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = ['https://*.deploy-gaes9-comgstore-production.up.railway.app']

MESSAGE_STORAGE = 'django.contrib.messages.storage.cookie.CookieStorage'

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'fontawesomefree',
    'django.contrib.admin',    
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'import_export',

]


SESSION_COOKIE_AGE = 60 * 60 * 24 * 1
LOGOUT_REDIRECT_URL ='login'

X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'comGStore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'comGStore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = db.MYSQL


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Enviar emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'creativecomunity121@gmail.com'
EMAIL_HOST_PASSWORD = 'uuctuemothadljvn' 
EMAIL_PORT = 587
EMAIL_USE_TLS = True


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
MEDIA_URL = 'media/'
MEDIAFILES_DIRS = (
    os.path.join(BASE_DIR,'media'),
)

STATIC_URL = 'static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {

    'site_title': 'Panel',
    "site_brand": "Administrador",
    # Welcome text on the login screen
    'welcome_sign': 'Bienvenido Administrador',
    'site_logo': 'images/ComGStore.png',
    'site_logo_classes': 'img-square',
    'custom_css': 'css/djAdmin.css',
    "show_ui_builder": True,

   
    "button_classes": {
        "primary": "btn btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success"
    },

    'icons' : {
        'auth.user' : 'fas  fa-user',
        'auth.Group' : 'fas fa-users',
        'Core.client' : 'fas fa-users',
        'Core.purchase' : 'fas fa-cash-register',
        'Core.delivery' : 'fas fa-truck',
        'Core.statedomicile' : 'fas fa-clipboard-list',
        'Core.inventorymovement' : 'fas fa-box',
        'Core.order' : 'fas fa-cart-arrow-down',
        'Core.permissions' : 'fas fa-light fa-user-shield',
        'Core.product' : 'fas fa-tags',
        'Core.supplier' : 'fas fa-solid fa-parachute-box',
        'Core.sales' : 'fas fa-money-bill',
        'Core.rol' : 'fas fa-users',
        'Core.user' : 'fas fa-user',
    },
}

JAZZMIN_UI_TWEAKS = {
    
    "theme": "sandstone",
    "sidebar": "sidebar-dark-danger",
    "navbar": "navbar-navy navbar-dark",
    "body_small_text": True,
    "sidebar_fixed": True,
    "navbar_fixed": True,
}