# Generated by Django 4.1 on 2022-10-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='cod_product',
            field=models.ManyToManyField(through='core.SalesDetail', to='core.product'),
        ),
    ]
