# Generated by Django 4.1 on 2022-10-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_salesdetail_options_alter_salesdetail_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesdetail',
            options={'ordering': ['id'], 'verbose_name': 'DetalleVenta', 'verbose_name_plural': 'Detalle_Ventas'},
        ),
        migrations.AlterModelTable(
            name='salesdetail',
            table='detalle_venta',
        ),
    ]
