# Generated by Django 4.1 on 2022-10-31 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_price_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile', verbose_name='Domiciliario'),
        ),
    ]
